<form action="/users" method="post">
    <div>
        <label>
            Nickname
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
    </div>
    <input type="submit" value="Sign Up">
</form>